language: objective-c
osx_image: xcode9.3

branches:
  only:
    - master

env:
  global:
    - LANG=en_US.UTF-8
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=HTTPParserC.xcodeproj
  matrix:
    # Latest devices
    - DESTINATION="platform=iOS Simulator,name=iPhone 8 Plus"           SCHEME="HTTPParserC iOS"
    - DESTINATION="platform=iOS Simulator,name=iPad Pro (12.9-inch)"    SCHEME="HTTPParserC iOS"
    - DESTINATION="platform=tvOS Simulator,name=Apple TV"               SCHEME="HTTPParserC tvOS"
    - DESTINATION="platform=macOS,arch=x86_64"                          SCHEME="HTTPParserC macOS"

    # Older devices
    - DESTINATION="platform=iOS Simulator,name=iPad 2,OS=8.1"           SCHEME="HTTPParserC iOS"
    - DESTINATION="platform=iOS Simulator,name=iPhone 5s,OS=8.1"        SCHEME="HTTPParserC iOS"
    - DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=9.0"         SCHEME="HTTPParserC iOS"
    - DESTINATION="platform=iOS Simulator,name=iPhone 6 Plus,OS=10.0"   SCHEME="HTTPParserC iOS"

before_install:
  - xcodebuild -version
  - xcodebuild -showsdks

script:
  # Produce a failure return code if any command errors
  - set -o pipefail

  # Build in Debug mode
  - xcodebuild clean build -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c;

  # Build in Release mode
  - xcodebuild clean build -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO | xcpretty -c;
