name: "HTTPParserC CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT: HTTPParserC.xcodeproj
  SCHEME: HTTPParserC

jobs:
  iOS:
    name: Build iOS
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ["iPhone 8", "iPhone 14 Pro", "iPad Air (5th generation)", "iPad Pro (9.7-inch)"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build iOS
        run: |
          set -o pipefail
          xcodebuild clean build -project "$PROJECT" -scheme "$SCHEME" -destination "platform=iOS Simulator,name=${{ matrix.destination }}" -configuration Release ONLY_ACTIVE_ARCH=NO | xcpretty -c;

  tvOS:
    name: Build tvOS
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ["Apple TV", "Apple TV 4K (3rd generation)"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build tvOS
        run: |
          set -o pipefail
          xcodebuild clean build -project "$PROJECT" -scheme "$SCHEME" -destination "platform=tvOS Simulator,name=${{ matrix.destination }}" -configuration Release ONLY_ACTIVE_ARCH=NO | xcpretty -c;

  macOS:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build macOS
        run: |
          set -o pipefail
          xcodebuild clean build -project "$PROJECT" -scheme "$SCHEME" -destination "platform=macOS,arch=x86_64" -configuration Release ONLY_ACTIVE_ARCH=NO | xcpretty -c;
